version: "3.5"
services:

  node1:
    container_name: node1
    image: "ghcr.io/kwkoo/artemis:2.20.0"
    ports:
      - 8161:8161
    volumes:
      - artemis-node1:/storage/instances/node1
    command:
      - /storage/instances/node1/bin/artemis
      - run

  node2:
    container_name: node2
    image: "ghcr.io/kwkoo/artemis:2.20.0"
    ports:
      - 8261:8161
    volumes:
      - artemis-node2:/storage/instances/node2
    command:
      - /storage/instances/node2/bin/artemis
      - run
    depends_on:
      - node1

volumes:
  artemis-node1:
    name: artemis-node1
    external: true
  artemis-node2:
    name: artemis-node2
    external: true
